SERVER_CODES = {
    "SESSION_NOT_FOUND": {"code": 1001, "message": "Session not found."},
    "TEAM_ALREADY_EXISTS": {"code": 1002, "message": "Team already exists in this session."},
    "INVALID_CANDIDATE_ID": {"code": 1003, "message": "Invalid candidate identifier."},
    "SESSION_VOICE_MAP_NOT_INITIALIZED": {"code": 1004, "message": "Session voice map not initialized."},
    "INTERNAL_SERVER_ERROR": {"code": 1005, "message": "Internal server error."},
    "CANDIDATE_NOT_FOUND": {"code": 1006, "message": "Candidate not found."},
    "PLAYER_NOT_FOUND": {"code": 1007, "message": "Player not found."},
    "ROUND_NOT_FOUND": {"code": 1008, "message": "Round not found."},
    "TEAM_NOT_FOUND": {"code": 1009, "message": "Team not found."},
    "INVALID_SESSION_STATUS": {"code": 1010, "message": "Invalid session status."},
    "CANDIDATE_ALREADY_EXISTS": {"code": 1011, "message": "Candidate already exists."},
    "PLAYER_ALREADY_EXISTS": {"code": 1012, "message": "Player already exists."},
    "ROUND_ALREADY_EXISTS": {"code": 1013, "message": "Round already exists."},
    "TEAM_NOT_IN_SESSION": {"code": 1014, "message": "Team is not part of the specified session."},
    "CANDIDATE_NOT_IN_SESSION": {"code": 1015, "message": "Candidate is not part of the specified session."},
    "PLAYER_NOT_IN_ROUND": {"code": 1016, "message": "Player is not part of the specified round."},
    "INVALID_REQUEST_DATA": {"code": 1017, "message": "Invalid request data."},
    "CANDIDATE_SPEECH_GENERATION_FAILED": {"code": 1018, "message": "Failed to generate candidate speech."},
    "SESSION_ALREADY_STARTED": {"code": 1019, "message": "Session has already started."},
    "SESSION_ALREADY_ENDED": {"code": 1020, "message": "Session has already ended."},
    "ROUND_ALREADY_STARTED": {"code": 1021, "message": "Round has already started."},
    "ROUND_ALREADY_ENDED": {"code": 1022, "message": "Round has already ended."},
    "INSUFFICIENT_COINS": {"code": 1023, "message": "Insufficient coins for the requested operation."},
    "LEADERBOARD_NOT_AVAILABLE": {"code": 1026, "message": "Leaderboard is not available for this session."},
    "GLOBAL_LEADERBOARD_NOT_AVAILABLE": {"code": 1027, "message": "Global leaderboard is not available."},
}